name: Procesar Datos Automáticamente
on:
  schedule:
    - cron: '0 12 * * *'  # Se ejecuta todos los días a las 12:00 UTC
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: pip install pandas

      - name: Ejecutar el script de procesamiento de datos
        run: python procesamiento_datos.py

      - name: Commit y Push de los datos procesados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add datos_procesados.csv
          git commit -m "Actualizar datos procesados automáticamente" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}